import json
import re
import ast

def parse_json_robustly(text: str) -> dict:
    """
    Extracts the first valid JSON object or array from a string and parses it robustly.
    Handles markdown codeblocks anywhere in text, single quotes, comments, trailing commas,
    and conversational wrappers.
    """
    if not text:
        raise ValueError("Empty response string received from LLM.")

    if hasattr(text, "content"):
        text = text.content

    if isinstance(text, list):
        blocks = [b.get("text", "") if isinstance(b, dict) else str(b) for b in text]
        text = "\n".join(blocks)

    text_clean = str(text).strip()
    
    # 1. Search for codeblock contents first
    cb_match = re.search(r"```(?:json|python)?\s*([\s\S]*?)\s*```", text_clean, re.IGNORECASE)
    if cb_match:
        text_clean = cb_match.group(1).strip()

    # 2. Collapse doubled braces {{ }} -> { } (LLMs mimic prompt template escaping)
    text_clean = text_clean.replace("{{", "{").replace("}}", "}")

    # 3. Try direct json.loads
    try:
        return json.loads(text_clean)
    except Exception:
        pass

    # 3. Strip JS-style single-line comments // ...
    text_clean = re.sub(r"//.*$", "", text_clean, flags=re.MULTILINE)

    # 4. Extract outer `{ ... }` or `[ ... ]`
    first_brace = text_clean.find('{')
    first_bracket = text_clean.find('[')
    
    start_idx = -1
    end_char = ''
    
    if first_brace != -1 and (first_bracket == -1 or first_brace < first_bracket):
        start_idx = first_brace
        end_char = '}'
    elif first_bracket != -1:
        start_idx = first_bracket
        end_char = ']'
        
    if start_idx != -1:
        end_idx = text_clean.rfind(end_char)
        if end_idx != -1 and end_idx > start_idx:
            candidate = text_clean[start_idx:end_idx + 1].strip()
            
            # Direct parse candidate
            try:
                return json.loads(candidate)
            except Exception:
                pass

            # Clean trailing commas
            candidate_cleaned = re.sub(r',\s*([\]}])', r'\1', candidate)
            try:
                return json.loads(candidate_cleaned)
            except Exception:
                pass

            # ast.literal_eval for single quotes
            try:
                evaluated = ast.literal_eval(candidate_cleaned)
                if isinstance(evaluated, (dict, list)):
                    return evaluated
            except Exception:
                pass

            # Replace single quotes with double quotes
            try:
                sq_fixed = re.sub(r"'([^'\\]*(?:\\.[^'\\]*)*)'", r'"\1"', candidate_cleaned)
                return json.loads(sq_fixed)
            except Exception:
                pass

    # 5. ast.literal_eval on full text
    try:
        evaluated = ast.literal_eval(text_clean)
        if isinstance(evaluated, (dict, list)):
            return evaluated
    except Exception:
        pass

    raise json.JSONDecodeError("Failed to parse JSON after multiple repair attempts.", text_clean, 0)


def clean_llm_markdown(text: str) -> str:
    """Removes leading/trailing codeblock wrappers if generated by the LLM."""
    clean = text.strip()
    if clean.startswith("```"):
        clean = re.sub(r"^```(?:markdown|text|json)?\n", "", clean)
        clean = re.sub(r"\n```$", "", clean)
        clean = clean.strip()
    return clean

